# Generated by Skyramp v1.3.34 on 2026-07-12 07:43:37.800868348 +0000 UTC m=+254.529008481
# Command: skyramp generate contract rest http://localhost:2285/users/me \
# 		--api-schema http://localhost:2285/api/spec.json \
# 		--auth-type Bearer \
# 		--framework pytest \
# 		--language python \
# 		--method GET \
# 		--output contract_get_users_me_owner_team.py \
# 		--output-dir /home/runner/work/immich/immich/tests/skyramp \
# 		--overwrite \
# 		--provider \
# 		--response-status-code 200 \
# 		--runtime local

# Import of required libraries
import skyramp
import os
import re


# URL for test requests
URL = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:2285")

# contract test for /users/me GET
def test_me_get():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Bearer " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Expected Response Body
    expected_me_GET_response_body = r'''{
        "avatarColor": "primary",
        "createdAt": "2024-01-01T00:00:00.000Z",
        "deletedAt": null,
        "email": "admin@immich.test",
        "id": "91ab9507-3101-433a-88de-a70c65218a8f",
        "isAdmin": true,
        "license": null,
        "name": "Admin",
        "oauthId": "",
        "profileChangedAt": "2026-07-12T07:43:37Z",
        "profileImagePath": "",
        "quotaSizeInBytes": null,
        "quotaUsageInBytes": 0,
        "shouldChangePassword": true,
        "status": "active",
        "storageLabel": "admin",
        "updatedAt": "2024-01-01T00:00:00.000Z"
    }'''

    # Execute Request
    me_GET_response = client.send_request(
        url=URL,
        path="/api/users/me",
        method="GET",
        headers=headers
    )

    # Generated Assertions
    assert me_GET_response.status_code == 200
    assert skyramp.check_schema(me_GET_response, expected_me_GET_response_body)
    assert skyramp.get_response_value(me_GET_response, "avatarColor") is not None
    assert skyramp.get_response_value(me_GET_response, "createdAt") is not None
    assert skyramp.get_response_value(me_GET_response, "deletedAt") is None
    uuid_pattern = r"^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$"
    iso_timestamp_pattern = r"^\d{4}-\d{2}-\d{2}T"
    user_id = skyramp.get_response_value(me_GET_response, "id")
    assert re.match(uuid_pattern, user_id, re.IGNORECASE)
    email = skyramp.get_response_value(me_GET_response, "email")
    assert "@" in email and "." in email.split("@")[1]
    assert re.match(iso_timestamp_pattern, skyramp.get_response_value(me_GET_response, "createdAt"))
    assert re.match(iso_timestamp_pattern, skyramp.get_response_value(me_GET_response, "updatedAt"))
    assert re.match(iso_timestamp_pattern, skyramp.get_response_value(me_GET_response, "profileChangedAt"))
    assert skyramp.get_response_value(me_GET_response, "isAdmin") in (True, False)
    assert skyramp.get_response_value(me_GET_response, "shouldChangePassword") in (True, False)
    quota_used = skyramp.get_response_value(me_GET_response, "quotaUsageInBytes")
    if quota_used is not None:
        assert quota_used >= 0
    # ownerTeam (added in this PR): optional and not populated by any mapper today, so it must
    # either be absent from the response or, if a future backfill sets it, a plain string.
    owner_team = skyramp.get_response_value(me_GET_response, "ownerTeam")
    assert owner_team is None or isinstance(owner_team, str)


if __name__ == "__main__":
    test_me_get()
