# Generated by Skyramp v1.3.34 on 2026-07-12 07:43:17.889665458 +0000 UTC m=+234.617805591
# Command: skyramp generate contract rest http://localhost:2285/admin/users \
# 		--api-schema http://localhost:2285/api/spec.json \
# 		--auth-type Bearer \
# 		--framework pytest \
# 		--language python \
# 		--method GET \
# 		--output contract_get_admin_users_owner_team.py \
# 		--output-dir /home/runner/work/immich/immich/tests/skyramp \
# 		--overwrite \
# 		--provider \
# 		--response-status-code 200 \
# 		--runtime local

# Import of required libraries
import skyramp
import os
import re


# URL for test requests
URL = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:2285")

# contract test for /admin/users GET
def test_users_get():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Bearer " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Expected Response Body
    expected_users_GET_response_body = r'''[
        {
            "avatarColor": "primary",
            "createdAt": "2024-01-01T00:00:00.000Z",
            "deletedAt": null,
            "email": "admin@example.com",
            "id": "e79c23af-ff2b-4e17-ba6d-0c8b1f2cd70a",
            "isAdmin": true,
            "license": null,
            "name": "Jane Doe",
            "oauthId": "",
            "profileChangedAt": "2026-07-12T07:43:17Z",
            "profileImagePath": "",
            "quotaSizeInBytes": null,
            "quotaUsageInBytes": 0,
            "shouldChangePassword": false,
            "status": "active",
            "storageLabel": null,
            "updatedAt": "2024-01-01T00:00:00.000Z"
        }
    ]'''

    # Execute Request
    users_GET_response = client.send_request(
        url=URL,
        path="/api/admin/users",
        method="GET",
        headers=headers,
        query_params={
            "id": None,
            "withDeleted": None
        }
    )

    # Generated Assertions
    assert users_GET_response.status_code == 200
    assert skyramp.check_schema(users_GET_response, expected_users_GET_response_body)
    assert skyramp.get_response_value(users_GET_response, "0.avatarColor") is not None
    assert skyramp.get_response_value(users_GET_response, "0.createdAt") is not None
    assert skyramp.get_response_value(users_GET_response, "0.deletedAt") is None
    uuid_pattern = r"^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$"
    iso_timestamp_pattern = r"^\d{4}-\d{2}-\d{2}T"
    user_id = skyramp.get_response_value(users_GET_response, "0.id")
    assert re.match(uuid_pattern, user_id, re.IGNORECASE)
    email = skyramp.get_response_value(users_GET_response, "0.email")
    assert "@" in email and "." in email.split("@")[1]
    assert re.match(iso_timestamp_pattern, skyramp.get_response_value(users_GET_response, "0.createdAt"))
    assert re.match(iso_timestamp_pattern, skyramp.get_response_value(users_GET_response, "0.updatedAt"))
    assert re.match(iso_timestamp_pattern, skyramp.get_response_value(users_GET_response, "0.profileChangedAt"))
    assert skyramp.get_response_value(users_GET_response, "0.isAdmin") in (True, False)
    assert skyramp.get_response_value(users_GET_response, "0.shouldChangePassword") in (True, False)
    quota_used = skyramp.get_response_value(users_GET_response, "0.quotaUsageInBytes")
    if quota_used is not None:
        assert quota_used >= 0
    # ownerTeam (added in this PR): optional and not populated by any mapper today, so it must
    # either be absent from the response or, if a future backfill sets it, a plain string.
    owner_team = skyramp.get_response_value(users_GET_response, "0.ownerTeam")
    assert owner_team is None or isinstance(owner_team, str)


if __name__ == "__main__":
    test_users_get()
