# Generated by Skyramp v1.3.34 on 2026-07-12 07:43:12.497738073 +0000 UTC m=+229.225878216
# Command: skyramp generate contract rest http://localhost:2285/albums \
# 		--api-schema http://localhost:2285/api/spec.json \
# 		--auth-type Bearer \
# 		--framework pytest \
# 		--language python \
# 		--method GET \
# 		--output contract_get_albums_owner_team.py \
# 		--output-dir /home/runner/work/immich/immich/tests/skyramp \
# 		--overwrite \
# 		--provider \
# 		--response-status-code 200 \
# 		--runtime local

# Import of required libraries
import skyramp
import os
import re
import uuid


# URL for test requests
URL = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:2285")

# contract test for /albums GET
def test_albums_get():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Bearer " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Setup: create an album so the list endpoint has a real, known item to assert against
    # (a fresh deployment starts with zero albums).
    album_name = "Contract Test Album 20260712-" + uuid.uuid4().hex[:8]
    albums_POST_response = client.send_request(
        url=URL,
        path="/api/albums",
        method="POST",
        headers=headers,
        body='{"albumName": "%s"}' % album_name
    )
    assert albums_POST_response.status_code == 201
    created_album_id = skyramp.get_response_value(albums_POST_response, "id")

    # Expected Response Body
    expected_albums_GET_response_body = r'''[
        {
            "albumName": "Contract Test Album 20260712",
            "albumThumbnailAssetId": null,
            "albumUsers": [
                {
                    "role": "owner",
                    "user": {
                        "avatarColor": "primary",
                        "email": "admin@immich.test",
                        "id": "c8bfbf31-be5d-489d-a2b2-8118bfbc4f32",
                        "name": "Admin",
                        "profileChangedAt": "2026-07-12T07:43:12Z",
                        "profileImagePath": ""
                    }
                }
            ],
            "assetCount": 0,
            "createdAt": "2026-07-12T07:43:12Z",
            "description": "",
            "hasSharedLink": false,
            "id": "a1b2c3d4-e5f6-7890-abcd-ef1234567890",
            "isActivityEnabled": true,
            "shared": false,
            "updatedAt": "2026-07-12T07:43:12Z"
        }
    ]'''

    # Execute Request
    albums_GET_response = client.send_request(
        url=URL,
        path="/api/albums",
        method="GET",
        headers=headers,
        query_params={
            "assetId": None,
            "id": None,
            "isOwned": None,
            "isShared": None,
            "name": None
        }
    )

    # Generated Assertions
    assert albums_GET_response.status_code == 200
    assert skyramp.check_schema(albums_GET_response, expected_albums_GET_response_body)
    # Albums are returned most-recently-created first, so the album created in setup is index 0.
    assert skyramp.get_response_value(albums_GET_response, "0.id") == created_album_id
    assert skyramp.get_response_value(albums_GET_response, "0.albumName") == album_name
    uuid_pattern = r"^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$"
    iso_timestamp_pattern = r"^\d{4}-\d{2}-\d{2}T"
    assert re.match(iso_timestamp_pattern, skyramp.get_response_value(albums_GET_response, "0.createdAt"))
    assert re.match(iso_timestamp_pattern, skyramp.get_response_value(albums_GET_response, "0.updatedAt"))
    assert skyramp.get_response_value(albums_GET_response, "0.shared") is False
    assert skyramp.get_response_value(albums_GET_response, "0.hasSharedLink") is False
    assert skyramp.get_response_value(albums_GET_response, "0.assetCount") == 0
    album_user_id = skyramp.get_response_value(albums_GET_response, "0.albumUsers.0.user.id")
    assert re.match(uuid_pattern, album_user_id, re.IGNORECASE)
    assert skyramp.get_response_value(albums_GET_response, "0.albumUsers.0.role") == "owner"
    assert re.match(iso_timestamp_pattern, skyramp.get_response_value(albums_GET_response, "0.albumUsers.0.user.profileChangedAt"))
    # ownerTeam (added in this PR): optional and not populated by any mapper today, so it must
    # either be absent from the response or, if a future backfill sets it, a plain string.
    owner_team = skyramp.get_response_value(albums_GET_response, "0.ownerTeam")
    assert owner_team is None or isinstance(owner_team, str)


if __name__ == "__main__":
    test_albums_get()
